language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-madridjs2' ]; then cd .. && eval "mv $currentfolder generator-madridjs2" && cd generator-madridjs2; fi

